name: complaint_vision
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.5.0
  image_picker: ^0.8.7+3
  permission_handler: ^10.0.0 
  provider: ^6.0.5
  intl: ^0.17.0 
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.1.0
  path: ^1.9.0
  firebase_app_check: ^0.2.0
  url_launcher: ^6.2.5
  geolocator: ^9.0.2      
  geocoding: ^3.0.0
  camera: ^0.10.5+9
  http: ^1.0.0
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/book.jpeg
    - lib/assets/images/fbicon.jpg
    - lib/assets/images/facebook_icon.png
    - lib/assets/images/google_icon.png
    - lib/assets/images/image.png
    - lib/assets/images/backg.jpg
    - lib/assets/images/vijay_paranthur.jpeg
    - lib/assets/images/min-thadai.webp
    - lib/assets/images/aritapatti_tun.avif
